### ISSUE TITLE
Any chance you could add this to bower?

### ISSUE THREAD

**Issue by byrnedo** [dmester/jdenticon#1]
http://bower.io/docs/creating-packages/

Or I guess I could do it for you maybe? I just think it would be useful personally since I use bower a lot for deps and I like your project :)

Edit: 
I just saw that bower takes a git repo too, it doesn't have to be in their registry.

**Comment by dmester** [comment]
Thanks for the tip! Seems like a good idea, I'll have a look at it.

**Comment by dmester** [comment]
Fixed!

**Comment by byrnedo** [comment]
Thanks!
