### ISSUE TITLE
Jdenticon is shown only after refreshing the page.

### ISSUE THREAD

**Issue by nikita-bosenko** [dmester/jdenticon#10]
So, when at first launch the jdenticon area is just white< but if I refresh the page image appears. I have even tried to use jdenticon.update(), but it doesn't help.
I attached file showing debugging info.
What information can I provide to clarify the problem?
Thank you
![capture](https://cloud.githubusercontent.com/assets/19288119/16342428/c7b33016-3a3a-11e6-87d4-ca04d7753278.PNG)

**Comment by nikita-bosenko** [comment]
And thank you for such a gret lib!:)

**Comment by dmester** [comment]
You're welcome :) Hard to tell the cause without knowing the context in which Jdenticon is used. I don't see any problems in the screenshot, so I have some questions.

1. Do you use the canvas or svg approach?
2. Are the svg/canvas elements delivered as static html or generated dynamically by using plain Javascript or a framework like Angular?
3. If using a framework, which one do you use?
4. Is the issue isolated to a single browser?

Regarding question 2 icons won't be automatically generated for DOM elements inserted after the initial page load.

**Comment by nikita-bosenko** [comment]
Thanks for your reply!
1. I use canvas.
2-3. Canvas elements are in templates which are used in different states(I am using Angular)
4. The issue is isolated to Google Chrome. In Edge icons are never generetated even after refreshing the page.

So is there any way to use Jdenticons with Angular?

**Comment by dmester** [comment]
The problem is that ```jdenticon.update``` is never called for canvases created dynamically as by Angular. A solution could be to create a directive that is responsible for calling ```jdenticon.update``` when the canvas element is constructed.

See this fiddle for an example:
https://jsfiddle.net/w5h6msvd/

Seems to work in Edge, IE, Chrome, FF and Opera.

**Comment by nikita-bosenko** [comment]
Hey, I have used this:

```
$('canvas').initialize( function(){
  jdenticon.update('.settings-avatar');
  jdenticon.update('.userpic');
});
```

and it worked:) Thank you

**Comment by vabtrix** [comment]
I am facing a similar problem while using Jidenticon with ReactJS. On state changes the icon just does not come up and update() does not work properly
