### ISSUE TITLE
Can u make render for img tag?

### ISSUE THREAD

**Issue by Luchanso** [dmester/jdenticon#12]
I need generate jpg/png for img tag, it is real? If you say how to do it, I can fork and write code himself and later will make merge request

**Comment by dmester** [comment]
Hi Luchanso,

It's not possible to generate a jpeg or png icon using Jdenticon. To be able to render a jpeg/png icon you would need to convert vector graphics to raster graphics. This is indeed possible using the HTML5 canvas feature, but then you could use a canvas right away to render icons without using an ```<img>``` element.

Here are some options:

## Canvas or SVG icons
If you don't need to support legacy browsers (IE8 and earlier) I would recommend to use canvas or SVG icons. See the examples below:

```html
<canvas width="80" height="80" data-jdenticon-hash="ff8adece0631821959f443c9d956fc39"></canvas>
<svg width="80" height="80" data-jdenticon-hash="ff8adece0631821959f443c9d956fc39"></svg>

<script src="https://cdn.jsdelivr.net/jdenticon/1.3.2/jdenticon.min.js"></script>
```
[Test run](https://jsfiddle.net/zr8ns8n0/)

## Data URIs
If you need to use ```<img>``` elements, but still don't need to support legacy browsers, you could create [data URIs](https://en.wikipedia.org/wiki/Data_URI_scheme) for SVG icons.

```html
<img src="fallbackurl.png" data-jdenticon-hash="ff8adece0631821959f443c9d956fc39" width="80" height="80">

<script src="https://cdn.jsdelivr.net/jdenticon/1.3.2/jdenticon.min.js"></script>
<script>
(function() {
    var icons = document.querySelectorAll("img[data-jdenticon-hash]");
    
    for (var i = 0; i < icons.length; i++) {
        var icon = icons[i],
            hash = icon.getAttribute("data-jdenticon-hash"),
            width = icon.width || icon.clientWidth || 400,
            height = icon.height || icon.clientHeight || 400,
            svg = jdenticon.toSvg(hash, Math.min(width, height));
            
        icon.src = "data:image/svg+xml," + encodeURIComponent(svg);
    }
})();
</script>
```
[Test run](https://jsfiddle.net/ocLswd17/)

## Server side icons
If you need to support legacy browsers you could generate the icons server side. For .NET check out [jdenticon-net](https://www.nuget.org/packages/Jdenticon-net/). For other platforms, it could be possible to run Jdenticon in a JavaScript engine, but I don't provide any support for this approach.

## Custom rasterization
If server side rendering is not an option and you need to support legacy browsers you would need to rasterize the shapes of the icon by yourself. This is a rather complex task, especially if antialiasing is required, but definitely possible. Very early versions of Jdenticon (which are not available in this repo) used this approach in the same way as [identicon.js](https://github.com/stewartlord/identicon.js) does, but this approach was abandoned as the icons became more complex. identicon.js might be a better base if you need to generate raster icons.

There is no plan to incorporate support for legacy browsers in Jdenticon, as I consider the market share for these browsers too low to justify the extra payload.
