### ISSUE TITLE
[Question] Are collisions possible for different hashes?

### ISSUE THREAD

**Issue by bryc** [dmester/jdenticon#13]
I am curious if jdenticon always produces a unique image for every input hash, or if there is a possibility that two different hash inputs could produce the same result.

I know collisions are always a theoretical possibility when condensing any amount of data into a fixed value, and the more bits generally reduces the amount of collisions, however..

jdenticon uses the hash itself, a minimum of 11 chars. So if we only use 11 hex digits, that is 44 bits of entropy, and **17,592,186,044,416** possible hash values.

Does jdenticon map 1:1 with those possible hash values? Are there that many unique jdenticon patterns?

**Comment by dmester** [comment]
This is an interesting question. Collisions are certainly possible, but according to my calculation (see below) Jdenticon is able to generate approximately 873,600 unique icons, meaning that the probability for a collision is 0.00011%.

This is what makes each icon unique:
* The pattern
* The colorization

# The pattern
Each icon is divided into a grid of 4x4 cells. Jdenticon places a shape in each of these cells. If the shape is not symmetrical, it can also be rotated 0, 90, 180 or 270 degrees.

Three shapes are selected and used in the icon:
* Corner shapes. Located in the four corner cells of the icon. 4 possible shapes (2 are symmetrical).
* Edge shapes. Located in the two cells between any pair of corner cells. 4 possible shapes (2 are symmetrical).
* Center shapes. Located in the four center cells of the icon. 14 possible shapes.

After considering that 2 of the corner and edge shapes can be rotated the number of possible shapes is increased:

* Corner shapes. 2 + 2 * 4 = 10
* Edge shapes. 2 + 2 * 4 = 10
* Center shapes. No rotation based on hash. Still 14.

Unique combinations: 10 * 10 * 14 = 1,400

# The colorization
Jdenticon uses the HSL model for selecting colors for the icon.

## Hue
28 bits of the hash are used to calculate the hue of the icon, which in theory yields 268,435,456 possible hues. As the number of hues are limited in terms of representable colors technically and by the user distinguishable colors, let's assume that a user can easily spot a difference in about 12 icons just differing in selected hues.

Unique combinations: 12

## Saturation, lightness
After selecting a hue, a combination of saturation and lightness for each shape category (corner, edge and center shapes) is selected from the following:
* Dark grey
* Light grey
* Dark color
* Middle color
* Light color

There are some constraints that will affect the number of possible combinations:
* The selected colors should be unique... 5 * 4 * 3 = 60
* ...except that the middle color is allowed to be duplicated. 60 + 4 = 64
* Dark grey + dark color combination is not allowed. 64 - 6 = 58
* Light grey + light color combination is not allowed. 58 - 6 = 52

Unique combinations: 52

# Total unique icons
1,400 * 12 * 52 = 873,600
