### ISSUE TITLE
supportsQuerySelectorAll returns false with Vue and webpack

### ISSUE THREAD

**Issue by layanto** [dmester/jdenticon#14]
Using jdenticon in a Vue component with webpack, supportsQuerySelectorAll returns false.
```javascript
supportsQuerySelectorAll = "document" in global && "querySelectorAll" in document
```
"document" in global returns false and "querySelectorAll" in document returns true.

**Comment by dmester** [comment]
Thanks for reporting this issue! I have reproduced the issue with the querySelectorAll feature detection when using Webpack and will include a fix for the issue in the next release of Jdenticon.
