### ISSUE TITLE
(Firefox) blank icon when svg width/height attribute is set to 100%

### ISSUE THREAD

**Issue by eugenexlin** [dmester/jdenticon#15]
When setting svg width and height to 100%, the icon appears as blank.
It seems to be caused by viewBox becoming 0 0 0 0, and the paths being calculated to everything 0.

I am trying to get an svg that scales to the parent element.

Only seems to happen for me on Firefox (using 51.0.1 32bit)

**Comment by dmester** [comment]
Thanks for reporting this issue! I have reproduced the issue and will include a fix in the next release of Jdenticon.
