### ISSUE TITLE
How many possible jdenticon's are there?

### ISSUE THREAD

**Issue by jcalfee** [dmester/jdenticon#19]
I would like to create an ID to go with the identicon (1 to 1 id to identicon).  The id should be as short as possible but no shorter.  So I need to know how many possible jdenticons could be created..

**Comment by dmester** [comment]
There is no easy answer to this question as some icons might appear exactly the same even if the color differs by 1%. [In a previous thread](https://github.com/dmester/jdenticon/issues/13#issuecomment-272720294) I approximated the number of different icons to 873,600.

Please note that you would need to reimplement [iconGenerator.js](https://github.com/dmester/jdenticon/blob/master/src/iconGenerator.js) to accomplish 873,600 unique icons by using an one-to-one id.
