### ISSUE TITLE
How to use it with NodeJS and save the image as a PNG?

### ISSUE THREAD

**Issue by yinanfang** [dmester/jdenticon#2]
Thank you for making this repo! Your identicon looks much better than others. Do you know if there's a way to use it with NodeJS and save the image on the server side and retrieve it later?

**Comment by dmester** [comment]
You’re welcome, I’m glad you like it! 

Jdenticon relies on HTML5 canvas for rendering the icons so as long as you provide a canvas context Jdenticon should be happy. I did some testing using Jdenticon with [node-canvas](https://github.com/Automattic/node-canvas) for rendering today and eventually got it working. Here is what I did:

1. Create an empty directory. Place [jdenticon.js from the nodejs branch](https://raw.githubusercontent.com/dmester/jdenticon/nodejs/jdenticon.js) there.

2. Install and build node-canvas in the directory created in step 1 according to these [installation instructions](https://github.com/Automattic/node-canvas/wiki/_pages). libjpeg-turbo is not needed for this test.

    If you run this on Windows, you might encounter the error message `Error: The specified module could not be found.` when running the test code. [Here is a solution](https://github.com/Automattic/node-canvas/issues/191) that helped me.

3. Create test.js with the following content:

```javascript
var Canvas = require("canvas"),
    jdenticon = require("./jdenticon"),
    fs = require("fs");

// Render identicon
var size = 200,
	canvas = new Canvas(size, size),
    ctx = canvas.getContext("2d");
jdenticon.drawIcon(ctx, "ff8adece0631821959f443c9d956fc39", size);

// Save as png file
var pngfile = fs.createWriteStream("./testicon.png"),
    stream = canvas.pngStream();
stream.on("data", function(chunk){
    pngfile.write(chunk);
});
stream.on("end", function(){
    console.log("saved png");
});
```

Run `node test.js`, cross your fingers and check testicon.png

**Comment by yinanfang** [comment]
Thank you so much for your help! 
I just looked at the installation wiki. I feel that there will not be any problem if I follow the instruction. However, I am using Webfaction as a server(https://www.webfaction.com/features). They use CentOS as the OS and I don't have sudo rights for installation since it's a share host. So I've been avoiding using package with dependencies. 
So thought of another solution. Get a Heroku server and put the image generation script on there. It seems to work but it harder to managed since it's separate. 

So my question is: do you know of any good canvas library without dependencies?

**Comment by dmester** [comment]
Sorry, I'm not aware of any canvas library without dependencies, but I've not used Node a lot.

One option would be to [generate svg files by implementing the canvas context interface](http://jsfiddle.net/bcmbLhwv/). However these svgs won't render correctly in some browsers, like IE, due to antialiasing of adjacent paths (ghost lines are visible in some icons). This can be solved by merging adjacent paths of the same color, but that is a rather complex task. Maybe there are some Node library rasterizing svgs without the antialiasing issue?

**Comment by yinanfang** [comment]
Hey. The code looks amazing!
So the these two lines save the svg to the html div
> jdenticon.drawIcon(ctx, md5, 200);
> document.getElementById("svg").innerHTML = ctx.toSvg();
It looks pretty good and I guess I don't need to support IE lol~
I found [svg2png](https://www.npmjs.com/package/svg2png), which can convert svg file to an png. I want to use png before the performance will be more stable across browser and I want to use it on my iPhone app, too. Is there a way that you can write a function that output a SVG file?

**Comment by dmester** [comment]
Sounds reasonable. As svg files are plain text xml files, you can simply write the output of toSvg() to a file, using ```fs```.

Here is an example:
https://gist.github.com/dmester/bdfe9d30c8def5382874

**Comment by yinanfang** [comment]
Oh!!! It works! That look amazing! And We don't have any dependencies! 
You should totally add that script to your libraries so that people and both use it on the front end and the back end!

**Comment by dmester** [comment]
That sounds great! My plan is to add svg support as an option in the core library once I have solved the issue with adjacent paths as mentioned in an earlier post. In addition to the increased flexibility in the library, the icons would also be much nicer rendered as svgs on high resolution devices.

**Comment by yinanfang** [comment]
Nice! I'm looking forward to using the better SVGs. Good luck with you work!
