### ISSUE TITLE
ReferenceError: requirejsVars is not defined. Error after running test file with enzyme, jest

### ISSUE THREAD

**Issue by huy23121994** [dmester/jdenticon#20]
I have a test suite to test file which import jdenticon. But when I run test, the error appear. What is this error?

**Comment by huy23121994** [comment]
Thanks @edwardEvans094 , the error gone :+1:

**Comment by dmester** [comment]
Thanks for reporting the issue, and I'm glad to hear that you have found a workaround.

I'm planning to remove the requirejs dependency from Jdenticon, since this is not the first time it has caused issues while running Jdenticon in non-browser environments. I'll keep you updated in this thread.

**Comment by dmester** [comment]
Jdenticon is no longer dependent on RequireJS as of version 1.8.0. This should solve this issue. Please get back if the issue remains.
