### ISSUE TITLE
Is it possible to limit the colour

### ISSUE THREAD

**Issue by MaryBartlett** [dmester/jdenticon#21]
I can see in colours.js you are doing a lot of work with the saturation and lightness. We would like to limit the colours used by e.g. sending some hex values or equivalent. Is this possible?

Thanks in advance

**Comment by dmester** [comment]
It depends on the degree of control over the colors you need. It is possible to limit (or extend) the saturation and lightness of the generated colors. You can find an example how to do this in [this example](https://jdenticon.com/js-api.html#jdenticon-config). However there is currently no option to control the hue of the colored shapes.

**Comment by MaryBartlett** [comment]
Thanks for your reply. It is the hue of the coloured shapes that we would want control of in order to conform with brand identity - although I realise it would probably need a lot of colours in order to make unique identicons. It looks as though it may be possible if I were to fork and extend the library so I might give that a go soon!
