### ISSUE TITLE
how to generate circle icon?

### ISSUE THREAD

**Issue by bulangnisi** [dmester/jdenticon#22]

**Comment by bulangnisi** [comment]
It can only generate rectangles. Can I generate a circle?

**Comment by dmester** [comment]
The easiest way to get Jdenticon render circular icons is to apply a `border-radius: 50%` CSS rule to your icons.

[Example](https://jsfiddle.net/amgLtz8h/)

However the corner shapes might be unwanted in a circular icon. To remove the corner shapes, you need to modify the code of Jdenticon. The code responsible for generating shapes is located in [iconGenerator.js](https://github.com/dmester/jdenticon/blob/master/src/iconGenerator.js). In the following example I have commented out line 80 in iconGenerator.js (line 914 in the example) to get rid of the corner shapes.

[Example](https://jsfiddle.net/zxz0mhcz/)

This approach requires that you replace the content of jdenticon.js in your application with the JavaScript specified in the example.

There are also other identicon libraries generating circular icons as their speciality, e.g. [Jazzicon](https://github.com/danfinlay/jazzicon).

**Comment by bulangnisi** [comment]
Thanks!This gave me a lot of help ^_^
