### ISSUE TITLE
No icon display in Ember.

### ISSUE THREAD

**Issue by Serpent6877** [dmester/jdenticon#29]
I have been trying to get this to work in Ember. Tried using NPM

npm install jdenticon@2.1.0

Tried adding it to my ember-cli-build.js and placing it in the vendor directory. Tried calling it directly in my index.html. Nada.

In my template I call:

<canvas width="80" height="80" data-jdenticon-value="{{block.miner}}"></canvas>

Any help appreciated.

Also note that this page: https://libraries.io/npm/jdenticon   in the getting started shows 2.0 still.

**Comment by dmester** [comment]
Jdenticon by default only renders icons once upon the initial page load. If new `canvas` or `svg` elements are inserted dynamically onto the page after this initial render, they won't be rendered automatically. 

To solve this issue you have two options:
* Call `jdenticon()` after new elements have been inserted onto the page. [Documentation](https://jdenticon.com/js-api.html#jdenticon)
* Enable the `observe` mode available in Jdenticon 2.1.0. When this mode is enabled Jdenticon will monitor the DOM tree for changes and render icons when needed. Note that the `observe` mode is not supported in IE10 and earlier. [Documentation](https://jdenticon.com/js-api.html#jdenticon-config)

I successfully rendered identicons in the ember-quickstart template app by enabling the `observe` mode. This is how I did:

### 1. Install Jdenticon using NPM

```
npm install jdenticon --save-dev
```

### 2. Update `ember-cli-build.js`

Add the following code to `ember-cli-build.js`:

```js
app.import('node_modules/jdenticon/dist/jdenticon.js', {
    using: [
        { transformation: 'amd', as: 'jdenticon' }
    ]
});
```

### 3. Enable `observe` mode

I enabled the `observe` mode by adding the following code to `app.js` but there are probably better places to do this initialization.

```js
import jdenticon from 'jdenticon';
jdenticon.config = {
  replaceMode: "observe"
};
```

**Comment by dmester** [comment]
Regarding https://libraries.io/npm/jdenticon, I missed to update the version number in the readme when releasing 2.1.0. Thanks for informing me! The version number is now updated in the repo, but since 2.1.0 is already released, the readme in NPM and other sites unfortunately won't be updated until the next release.

**Comment by Serpent6877** [comment]
I followed your example but still can't seem to get it to render. I have tried many ways. Tried ember-browserify as well. It just doesn't seem to fire off. Is there another way with possibly a helper?

This is the only way I was able to make it work. However the icons don't render on the initial page load. Only after 5 seconds which is the time that my refresh occurs.

format-jdenticon.js:
import Ember from 'ember';
import jdenticon from 'jdenticon';

export function formatjdenticon(value) {

        jdenticon.update("#identicon", value);
        return;
}

export default Ember.Helper.helper(formatjdenticon);

app/templates/test.hbs:
                  <canvas id="identicon" width="100" height="100"></canvas>
                  {{format-jdenticon}}

**Comment by dmester** [comment]
I have some questions that will help me better understand your setup:

* Which Ember version do you use?
* Which browser do you use?
* What does your Handlebars markup for the actual icons look like?
* Do you use SVG or CANVAS elements as icon placeholders?
* Do you use the `data-jdenticon-hash` or the `data-jdenticon-value` attribute on the placeholder elements?

Regarding using `jdenticon.update` from a helper, the problem is probably that the helper is called before the constructed html elements are actually inserted into the page.

You could try something like this:

```js
import { helper } from '@ember/component/helper';
import { htmlSafe } from '@ember/string';
import jdenticon from 'jdenticon';

// Counter used to give each icon a unique id
var jdenticonCounter = 0;

export function identicon([value, size]) {
    var iconId = "jdcn" + (jdenticonCounter++);

    // Schedule call to jdenticon.update
    setTimeout(() => jdenticon.update(`#${iconId}`, value), 0);

    return htmlSafe(`<svg id="${iconId}" width="${size}" height="${size}"></svg>`);
}

export default helper(identicon);
```

Usage in template:

```hbs
Icon: {{identicon "value" 60}}
```

**Comment by Serpent6877** [comment]
ember-cli: 2.91
Chrome 56

Handlebar: 
`import Ember from 'ember';
import jdenticon from 'jdenticon';

export function formatjdenticon(value) {

        console.log('Format');
        jdenticon.update("#identicon", value);
        jdenticon.update("#identicon", value);
        console.log('FormatAfter');
        return;
}

export default Ember.Helper.helper(formatjdenticon);
`

Template:
`{{format-jdenticon (block.miner)}}`

I tested with canvas and SVG. I was told in ember help I should use SVG however. I tested with hash and value. Since it is already a hash (an ethereum address) I assume hash would be best.

I tried your above. I get the following browser console error and I can't track down why.

Uncaught TypeError: e.create is not a function
    at y (vendor-a0be2a5….js:8)
    at Function.f.create (vendor-a0be2a5….js:8)
    at Object.d [as component] (vendor-a0be2a5….js:7)
    at S (vendor-a0be2a5….js:17)
    at Object.D [as inline] (vendor-a0be2a5….js:17)
    at Object.inline (vendor-a0be2a5….js:17)
    at l.populateNodes (vendor-a0be2a5….js:17)
    at l.render (vendor-a0be2a5….js:17)
    at Object.a [as default] (vendor-a0be2a5….js:17)
    at vendor-a0be2a5….js:17

**Comment by dmester** [comment]
Did you try placing identicon.js in app/helpers?

**Comment by dmester** [comment]
Did you also convert the helper to match your Ember version? I had to modify identicon.js as below to run it in ember-cli 2.9.1.

**app/helpers/identicon.js**

```js
import jdenticon from 'jdenticon';
import Ember from 'ember';

var jdenticonCounter = 0;

export function identicon([value, size]) {
  var iconId = "jdcn" + (jdenticonCounter++);

  // Schedule call to jdenticon.update
  setTimeout(() => jdenticon.update(`#${iconId}`, value), 0);

  return Ember.String.htmlSafe(`<svg id="${iconId}" width="${size}" height="${size}"></svg>`);
}

export default Ember.Helper.helper(identicon);
```

**ember-cli-build.js**

```js
app.import('vendor/jdenticon.js', {
  using: [
      { transformation: 'amd', as: 'jdenticon' }
  ]
});
```

**Template file**

```hbs
<h1>Jdenticon test</h1>
Test icons: 
{{identicon "value1" 60}}
{{identicon "value2" 60}}
```

**Result**

![Result](https://jdenticon.com/hosted/issue29.png)

**Comment by Serpent6877** [comment]
This seems to work and draw them instantly. But I have a page refresh that occurs every 5 seconds which causes the icons to blink. You can see it here:  http://fe.digipools.org/#/blocks  Next to "Mined By". Not sure how to handle that part. 

I do appreciate the help so far. I have learned a few things for sure.

**Comment by Serpent6877** [comment]
I also see in the code: https://github.com/dmester/jdenticon/blob/master/dist/jdenticon.js there is a toSvg function. Couldn't I call that directly from my helper instead of forcing an update each time?

**Comment by Serpent6877** [comment]
Alright get a good nights sleep and reading over the code here is the simple solution that will work for any ember.

app/helpers/identicon.js
`import jdenticon from 'jdenticon';
import Ember from 'ember';
import { helper } from '@ember/component/helper';

export function identicon([value, size]) {

  var icon = jdenticon.toSvg(value, size, "0");     

  return Ember.String.htmlSafe(icon);
}

export default helper(identicon);
`

app/templates/mytemplate.hbs
`{{identicon "MyIconValue" 60}}`

**Comment by dmester** [comment]
You're completely right, I didn't think of that. I'm glad you solved it and thanks for sharing the code!
