### ISSUE TITLE
Import downloaded version in Typescript

### ISSUE THREAD

**Issue by Kokogino** [dmester/jdenticon#30]
I want to download Jdenticon and import it that way:

    <script type="text/javascript" src="../node_modules/jdenticon/dist/jdenticon.min.js"></script>

This leads to this error on the console:

    Refused to execute script from 'http://localhost:4200/app/node_modules/jdenticon/dist/jdenticon.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

If I change the MIME type to ``'text/html'``, there's no error anymore but it just doesn't work.
However, if I import it like this:

    <script src="https://cdn.jsdelivr.net/npm/jdenticon@2.1.0" async></script>

everything works fine, but I want to use the downloaded version.

**Comment by dmester** [comment]
Did you check if http://localhost:4200/app/node_modules/jdenticon/dist/jdenticon.min.js is accessible in the browser? If the url is wrong, the web server will probably respond with an error page served as `text/html`.
