### ISSUE TITLE
How many distinct jdenticons exist?

### ISSUE THREAD

**Issue by icarroll** [dmester/jdenticon#32]
I am creating jdenticons from a 32-byte Ed25519 public key. What's the likelihood of two keys generating identical jdenticons?

**Comment by icarroll** [comment]
Sorry, I found the previous version of this question. Nearly a million it looks like.

**Comment by dmester** [comment]
For others ending up here, please see [issue #13](https://github.com/dmester/jdenticon/issues/13#issuecomment-272720294) for an approximation of the number of unique icons.
