### ISSUE TITLE
Generated image padding

### ISSUE THREAD

**Issue by sbwMikael** [dmester/jdenticon#34]
Hello - really impressed by the library, I'm evaluating it because I'm thinking of switching from server to client-side generated identicons.

My question is regards the padding added to each generated image. It looks like the padding is calculated in the 'iconGenerator' function. Is there any chance this could be added to the config? 

Only, my PHP generated identicons are exactly 32 x 32, but to achieve the same visual proportions with jdenticon I have to specify 40 x 40, and the side effect of this is that it distends the container.

If I hard code the 'padding' variable to 0, and then set my canvas size to 32 x 32, everything works as expected, but I don't like editing third-party libraries because (even with careful notes) I invariably forget what I've changed.

Thank you

**Comment by dmester** [comment]
Thanks for your suggestion! Sounds like a good idea as it would make the configuration more plattform independent. I will add it to the next release.

**Comment by sbwMikael** [comment]
Thank you very much!

**Comment by dmester** [comment]
Fixed in v 2.2.0. [Documentation](https://jdenticon.com/js-api/P_jdenticon_config.html#properties)
