### ISSUE TITLE
Angular 10 - CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by alegauss** [dmester/jdenticon#37]
```typescript
import { Directive, ElementRef, Input, OnChanges, SimpleChanges } from '@angular/core';
import { update } from "jdenticon";
@Directive({ selector: '[identiconHash]' })
export class IdenticonHashDirective implements OnChanges {
  @Input() identiconHash: string;

  constructor(private el: ElementRef) { }

  ngOnChanges(changes: SimpleChanges) {
    update(this.el.nativeElement, this.identiconHash);
  }
}
```
I created the following directive using 'jdenticon' on Angular 10 based on https://gist.github.com/mahsaml90/a908fc7b3085927119db4f9c606d85f6 and it is showing the following warning:

```
WARNING in <project>/src/app/directive/identicon-hash.directive.ts depends on 'jdenticon'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
Maybe you need convert CommonJS to ES6. (https://github.com/nolanlawson/cjs-to-es6#readme)

Regards,

**Comment by dmester** [comment]
Thanks for reporting this issue! I will have a look at it for the next version of Jdenticon.

Until a new version is available, you can add Jdenticon to [allowedCommonJsDependencies in angular.json](https://angular.io/guide/build#configuring-commonjs-dependencies) to get rid of the warning and acknowledge that angular-cli won't be able to eliminate code you're not using from Jdenticon. Jdenticon does not use any third-party packages and most of the codebase is in use when you use the library, so the effect on your application bundle size will most likely be minimal.

**Comment by dmester** [comment]
I have just released a new version of Jdenticon that should get rid of this warning by exposing an ES module based bundle. You should not need to do anything more than updating the Jdenticon dependency to version 3.0.0.

There is now also a brand new Angular package on NPM: [ngx-jdenticon](https://www.npmjs.com/package/ngx-jdenticon).
