### ISSUE TITLE
Input hash must be at least 11 chars

### ISSUE THREAD

**Issue by dalgard** [dmester/jdenticon#4]
On the library's homepage it says that the hash must be at least 10 chars long, but it is actually 11, since this code line [L487](https://github.com/dmester/jdenticon/blob/master/jdenticon.js#L478) ends up doing `charAt(10)`.

Jdenticon fails with a 10 char hash.

**Comment by dmester** [comment]
That is absolutely true, thanks for letting me know! I have updated the documentation and code.
