### ISSUE TITLE
Feature request: expose configurable hashing function?

### ISSUE THREAD

**Issue by zekenie** [dmester/jdenticon#47]
I _love_ jdenticon!

I'm working on a project now that could use it in an unconventional way. I want to show a table of webhooks my service receives, and visually represent _similar_ requests. I was thinking of using jdenticon with a hash function designed to optimize collisions as opposed to avoid them (for example the [Nilsimsa](https://en.wikipedia.org/wiki/Nilsimsa_Hash) hash). To do that, I would need to be able to pass jdenticon a hash function. How would you all feel about exposing a configurable hash? I'd be happy to put up a PR for it.

**Comment by zekenie** [comment]
I believe I've found that you kind of already do this. Am I correct in saying that if I pass a valid hexadecimal string, it will not be hashed, and it will be rendered directly?

**Comment by dmester** [comment]
Yes, you're correct.
