### ISSUE TITLE
Make saturation configurable

### ISSUE THREAD

**Issue by dalgard** [dmester/jdenticon#5]
As much as I like the visual style of this library, I would like to be able to customize the saturation of the icons so that they will fit the visual scheme of my website better.

It would be great to have saturation be configurable instead of always being 0.5.

**Comment by dmester** [comment]
That is a great idea! I will think of how this is best implemented and hopefully, this will be included in the next version. Thanks for the suggestion!

**Comment by dalgard** [comment]
No, thank you :)
