### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Pawtiko** [dmester/jdenticon#7]
I was hoping that, for simple ease of use, it would be possible to download the jdenticons produced via the demo on your website. I used to be able to do this by right clicking on the image, however I believe that your switching over to SVG rendering has made that impossible. I found it very useful to download the raw image without running any code myself. In fact, this is how I got my current avatar.

**Comment by dmester** [comment]
Good point, thanks for noticing! Now it should be possible to right-click and save the icon again in supported browsers. You might need to CTRL+F5 the demo page to ensure a cached version of the page is not used.
