### ISSUE TITLE
Polymer version is available

### ISSUE THREAD

**Issue by MeTaNoV** [dmester/jdenticon#8]
Hi,
really nice work!
I used your library to create a Polymer component.
Feel free to reference it in whatever way!
You can find it part of a set: https://github.com/MeTaNoV/firebase-element-extended
Thanks again for the nice job!
Cheers,
Pascal

**Comment by dmester** [comment]
Nice work, and thanks for informing me! It's always of interest to see how other make use of the library.

I have planned to improve the documentation of various ways of using Jdenticon when I have time, and the Polymer component could definitely be one of those. I will keep this in mind when I do that.

**Comment by MeTaNoV** [comment]
I will probably extract it from this set and make it standalone, I'll keep you informed!

**Comment by MeTaNoV** [comment]
Hi,
just finished releasing `identicon-element` as a standalone Polymer element, feel free to check it out and comment!
https://github.com/MeTaNoV/identicon-element
Cheers,
Pascal

**Comment by dmester** [comment]
Sorry for not getting back to you sooner. I have added a reference to the Polymer component in the GitHub readme for Jdenticon.

**Comment by MeTaNoV** [comment]
Thx! :)
